name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Kodu İndir
        uses: actions/checkout@v4
        
      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bağımlılıkları Yükle
        shell: bash
        run: |
          rm -f package-lock.json
          npm install

      - name: Uygulamayı Derle ve GitHub'a Yükle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: npm run electron:build -- -p always
